version: '3'

services:
  master:
    image: locustio/locust:master
    ports:
      - "8089:8089"
    volumes:
      - /host:/mnt/locust
    #  - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master
  worker:
    image: locustio/locust:master
    volumes:
      - /host:/mnt/locust
    #  - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
