server:
  port: 9900

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fpdjsns/MSA-config-files.git
#    bus:
#      destination: springCloudBus
  kafka:
    bootstrap-servers: {{your.host.name}}:9092
