server:
  port: 8888

spring:
  application:
    name: config-server
  main:
    allow-bean-definition-overriding: true
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fpdjsns/MSA-config-files.git
#    bus:
#      destination: springCloudBus
      monitor:
#        custom:
#          profiles: dev, alpha, real, beta
  kafka:
    bootstrap-servers: {{your.host.name}}:9092

logging:
  level:
    root: INFO
    org:
      apache:
        kafka: INFO
