server:
  port: 9900

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fpdjsns/MSA-config-files.git
#    bus:
#      destination: springCloudBus
      monitor:
        endpoint:
          path: /actuator
  kafka:
    bootstrap-servers: {{your.host.name}}:9092

logging:
  level:
    root: INFO
    org:
      apache:
        kafka: INFO
