server:
  port: 9901
#  port: 9902

spring:
  application:
    name: config-client
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:9900
#    bus:
#      destination: springCloudBus
  kafka:
    bootstrap-servers: {{your.host.name}}:9092

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh
